# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_questions_ok', models.IntegerField()),
                ('count_questions_fail', models.IntegerField()),
                ('count_exams_pass', models.IntegerField()),
                ('count_exams_fail', models.IntegerField()),
                ('exam_pass_average', models.FloatField()),
                ('exam_fail_average', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
