# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170727_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='count_exams_fail',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_exams_pass',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_questions_fail',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_questions_ok',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='exam_fail_average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stats',
            name='exam_pass_average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
    ]
