# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170727_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='count_exams_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_exams_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_questions_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='count_questions_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='exam_fail_average',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stats',
            name='exam_pass_average',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
