# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170727_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='exam_fail_average',
            new_name='exam_fail_total_score',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='exam_pass_average',
            new_name='exam_pass_total_score',
        ),
    ]
