# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=200)),
                ('example', models.CharField(max_length=200)),
                ('variable', models.CharField(max_length=50)),
                ('sub_variable', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=100)),
                ('url_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='MenuReader',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='SubjectReader',
            new_name='Subject',
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datareader.Subject'),
        ),
    ]
