# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0003_auto_20170417_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='theme',
            new_name='topic',
        ),
    ]
