# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0006_subtopic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subtopics_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(default=-1),
        ),
    ]
