# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0009_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('vf', 'verdadero falso'), ('opm', 'opcion multiple')], default='vf', max_length=2),
        ),
    ]
